name: "Automerge Pull Requests"
# Note: This workflow only triggers when labels are added manually.
# When labels are added by GitHub Actions (using GITHUB_TOKEN), 
# this workflow won't trigger due to GitHub's security features.
# Programmatic automerge is handled in label-validated-prs.yml
on:
  pull_request_target:
    types: [labeled, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
  
  remove-label-on-new-commit:
    if: github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Remove automerge label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          labels: automerge
      
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔄 New commit detected. The automerge label has been removed. It will be re-added if validation passes.'
            })