name: "Handle Manual Automerge"
# This workflow handles manual automerge label additions and new commits.
# The automatic flow (validation -> label -> automerge) is handled by pull-request-complete.yml
on:
  pull_request:
    types: [labeled, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  handle-manual-automerge:
    if: github.event.action == 'labeled' && contains(github.event.label.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is manual addition
        id: check_manual
        run: |
          # Check if the label was added by a human (not a bot/action)
          ACTOR="${{ github.actor }}"
          if [[ "$ACTOR" != *"[bot]"* ]] && [[ "$ACTOR" != "github-actions" ]]; then
            echo "is_manual=true" >> $GITHUB_OUTPUT
            echo "✅ Manual label addition by $ACTOR"
          else
            echo "is_manual=false" >> $GITHUB_OUTPUT
            echo "❌ Automated label addition, skipping"
          fi
      
      - name: Enable auto-merge for manual label
        if: steps.check_manual.outputs.is_manual == 'true'
        run: |
          echo "🔄 Enabling auto-merge for manually labeled PR #${{ github.event.pull_request.number }}"
          gh pr merge ${{ github.event.pull_request.number }} \
            --squash \
            --auto \
            --delete-branch \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  remove-label-on-new-commit:
    if: github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Remove automerge label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          labels: automerge
      
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔄 New commit detected. The automerge label has been removed. It will be re-added if validation passes.'
            })