name: "Automerge After All Checks"
on:
  check_suite:
    types: [completed]

permissions:
  pull-requests: write
  contents: write
  checks: read

jobs:
  automerge:
    if: github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        id: pr_details
        run: |
          # Get associated pull requests
          if [ -z "${{ github.event.check_suite.pull_requests[0].number }}" ]; then
            echo "No PR associated with this check suite"
            echo "should_proceed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          PR_NUMBER="${{ github.event.check_suite.pull_requests[0].number }}"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          
          # Get PR details including labels and status
          PR_DATA=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER)
          
          # Check if PR has automerge label
          HAS_AUTOMERGE=$(echo "$PR_DATA" | jq -r '.labels[] | select(.name == "automerge") | .name')
          
          if [ "$HAS_AUTOMERGE" = "automerge" ]; then
            echo "✅ PR #$PR_NUMBER has automerge label"
            
            # Check if ALL required checks have passed
            CHECK_RUNS=$(gh api repos/${{ github.repository }}/commits/${{ github.event.check_suite.head_sha }}/check-runs --jq '.check_runs')
            
            # Count total checks and successful checks
            TOTAL_CHECKS=$(echo "$CHECK_RUNS" | jq 'length')
            SUCCESSFUL_CHECKS=$(echo "$CHECK_RUNS" | jq '[.[] | select(.conclusion == "success")] | length')
            PENDING_CHECKS=$(echo "$CHECK_RUNS" | jq '[.[] | select(.status != "completed")] | length')
            
            echo "Check status: $SUCCESSFUL_CHECKS/$TOTAL_CHECKS successful, $PENDING_CHECKS pending"
            
            if [ "$PENDING_CHECKS" -eq 0 ] && [ "$SUCCESSFUL_CHECKS" -eq "$TOTAL_CHECKS" ]; then
              echo "✅ All checks have passed!"
              echo "should_proceed=true" >> $GITHUB_OUTPUT
            else
              echo "⏳ Not all checks have passed yet"
              echo "should_proceed=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "❌ PR #$PR_NUMBER does not have automerge label"
            echo "should_proceed=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Merge PR
        if: steps.pr_details.outputs.should_proceed == 'true'
        run: |
          PR_NUMBER="${{ steps.pr_details.outputs.pr_number }}"
          echo "🔀 Merging PR #$PR_NUMBER"
          gh pr merge $PR_NUMBER --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 